server:
  port: 8080
  
http:
    end-point: /core-base  
    
management:
   endpoints:
      web:
         exposure:
            include: info, health , mappings , integrationgraph
    
spring:
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/musicbrainz
    url: jdbc:postgresql://127.0.0.1:5432/musicbrainz
    username: postgres 
    password: postgres123@   
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        ddl-auto: update
        javax:
         cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache:
           use_second_level_cache: true
           use_query_cache: true
           #region:
              #factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  ehcache:
      config: classpath:ehcache.xml                  
  properties:
    javax:
      persistence:
        sharedCache: 
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
        mode: ENABLE_SELECTIVE         

entitymanager:
  packagesToScan: org.nanotek

artist:
  fileLocation: /opt/mbdump
  fileName: artist
  id: ArtistBean
  type: org.nanotek.beans.csv.ArtistBean
  baseMap:
    id: 0
    gid: 1
    name: 2
    sortName: 3
    beginDateYear: 4
    beginDateMonth: 5
    beginDateDay: 6
    endDateYear: 7
    endDateMonth: 8
    endDateDay: 9
    type: 10
    area: 11
    gender: 12 
    comment: 13
    editsPending: 14
    lastUpdated: 15
    ended: 16
    beginArea: 17
    endArea: 18

    
artistalias:
  fileLocation: /opt/mbdump
  fileName: artist_alias
  id: ArtistAlias
  type: org.nanotek.beans.entity.ArtistAlias
  baseMap:  
    id: 0
    artistId: 1
    alias: 2
    locale: 3
    editsPending: 4
    lastUpdated: 5
    type: 6
    sortAlias: 7
    beginDateYear: 8
    beginDateMonth: 9
    beginDateDay: 10
    endDateYear: 11
    endDateMonth: 12
    endDateDay: 13
    primaryForLocale: 14
    ended: 15
    
artistcredit:
  fileLocation: /opt/mbdump
  fileName: artist_credit1
  id: ArtistCreditBean
  type: org.nanotek.beans.csv.ArtistCreditBean
  baseMap:  
    id: 0
    name: 1
    artistCount: 2
    refCount: 3
    created: 4
    editsPending: 5

artistcreditname:
  fileLocation: /opt/mbdump
  fileName: artist_credit_name
  id: ArtistCreditName
  type: org.nanotek.beans.entity.ArtistCreditName
  baseMap:  
    artistCredit: 0
    position: 1            
    artist: 2              
    name: 3                
    joinPhrase: 4    
 
artistcreditnamebean:
  fileLocation: /opt/mbdump
  fileName: artist_credit_name
  id: ArtistCreditNameBean
  type: org.nanotek.beans.csv.ArtistCreditNameBean
  baseMap:  
    artistCreditId: 0
    position: 1            
    artistId: 2              
    name: 3                
    joinPhrase: 4      
    
    
releasebean: 
  fileLocation: /opt/mbdump
  fileName: release
  id: ReleaseBean
  type: org.nanotek.beans.csv.ReleaseBean 
  baseMap: 
    id: 0 
    gid: 1 
    name: 2
    artistCreditId: 3 
    releaseGroup: 4 
    status: 5 
    packaging: 6 
    language: 7 
    script: 8
    barcode: 9 
    comment: 10 
    editsPending: 11 
    quality: 12 
    lastUpdated: 13
    
releasegroup: 
  fileLocation: /opt/mbdump
  fileName: release_group
  id: ReleaseGroupBean
  type: org.nanotek.beans.csv.ReleaseGroupBean 
  baseMap:   
    id: 0 
    gid: 1 
    name: 2 
    artistCredit: 3 
    type: 4
    comment: 5 
    editsPending: 6
    lastUpdated: 7
 
recordingbean: 
  fileLocation: /opt/mbdump
  fileName: recording1
  id: RecordingBean
  type: org.nanotek.beans.csv.RecordingBean 
  baseMap:   
    id: 0
    gid: 1
    name: 2
    artistCredit: 3
    length: 4
    comment: 5
    editsPending: 6
    lastUpdated: 7
    video: 8

trackbean: 
  fileLocation: /opt/mbdump
  fileName: track
  id: TrackBean
  type: org.nanotek.beans.csv.TrackBean 
  baseMap:    
    id: 0 
    gid: 1 
    recordingId: 2 
    medium: 3 
    position: 4 
    number: 5 
    name: 6 
    artistCreditId: 7 
    length: 8 
    editsPending: 8 
    lastUpdate: 9
    isDataTrack: 10
    
mediumbean: 
  fileLocation: /opt/mbdump
  fileName: medium
  id: MediumBean
  type: org.nanotek.beans.csv.MediumBean 
  baseMap:     
    id: 0
    release: 1 
    position: 2
    format: 3 
    name: 4 
    editsPending: 5 
    lastUpdated: 6 
    trackCount: 7 
    
artisttype: 
  fileLocation: /opt/mbdump
  fileName: artist_type
  id: ArtistType
  type: org.nanotek.beans.entity.ArtistType 
  baseMap:     
    id: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5

instrumenttype:
  fileLocation: /opt/mbdump
  fileName: instrument_type
  id: InstrumentTypeBean
  type: org.nanotek.beans.csv.InstrumentTypeBean 
  baseMap:     
    id: 0
    name: 1
    parent: 2
    child_order: 3
    description: 4
    gid: 5

instrument:
  fileLocation: /opt/mbdump
  fileName: instrument
  id: InstrumentBean
  type: org.nanotek.beans.csv.InstrumentBean 
  baseMap:     
    id: 0
    gid: 1
    name: 2
    type: 3
    editsPending: 4
    lastUpdatead: 5
    comment: 6 
    description: 7

releasegroupprimarytype:
  fileLocation: /opt/mbdump
  fileName: release_group_primary_type
  id: ReleaseGroupPrimaryTypeBean
  type: org.nanotek.beans.csv.ReleaseGroupPrimaryTypeBean
  baseMap:  
      id: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5
      
releasestatus:
  fileLocation: /opt/mbdump
  fileName: release_status
  id: ReleaseStatusBean
  type: org.nanotek.beans.csv.ReleaseStatusBean
  baseMap:  
      id: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5 

releasepackaging:
  fileLocation: /opt/mbdump
  fileName: release_packaging
  id: ReleasePackagingBean
  type: org.nanotek.beans.csv.ReleasePackagingBean
  baseMap:  
      id: 0 
      name: 1 
      parent: 2 
      childOrder: 3 
      description: 4 
      gid: 5            

language:
  fileLocation: /opt/mbdump
  fileName: language
  id: LanguageBean
  type: org.nanotek.beans.csv.LanguageBean
  baseMap:  
      id: 0 
      isoCode2t: 1 
      isoCode2b: 2 
      isoCode1: 3 
      name: 4 
      frequency: 5 
      isoCode3: 6            

csv-endpoint:
   instrument-type: /csv/instrument 
   map-config: /map_config
   reopen: /reopen_file
   next: /next
   next_entity: /next_entity
   load: /load
