server:
  port: 8081
  
http:
    end-point: /core-base  

spring:
  activemq:
   broker-url: tcp://localhost:61616
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/music-brainz
    url: jdbc:postgresql://127.0.0.1:5432/music-brainz
    username: postgres 
    password: Postgres123@   
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 100
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

entitymanager:
  packagesToScan: org.nanotek

artist:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist
  id: Artist
  type: org.nanotek.beans.ArtistName
  baseMap:
    artistId: 0
    gid: 1
    name: 2
    sortName: 3
    begin-date-year: 4
    begin-date-month: 5
    begin-date-day: 6
    end-date-year: 7
    end-date-month: 8
    end-date-day: 9
    type: 10
    area: 11
    gender: 12 
    comment: 13
    edits-pending: 14
    last-updated: 15
    ended: 16

    
artistalias:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist_alias
  id: ArtistAlias
  type: org.nanotek.beans.ArtistAlias
  baseMap:  
    id: 0
    artistId: 1
    alias: 2
    locale: 3
    editsPending: 4
    lastUpdated: 5
    type: 6
    sortAlias: 7
    beginDateYear: 8
    beginDateMonth: 9
    beginDateDay: 10
    endDateYear: 11
    endDateMonth: 12
    endDateDay: 13
    primaryForLocale: 14
    ended: 15
    
artistcredit:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist_credit
  id: ArtistCredit
  type: org.nanotek.beans.ArtistCredit
  baseMap:  
    artistCreditId: 0
    name: 1
    artistCount: 2
    refCount: 3
    created: 4
    editsPending: 5

artistcreditname:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist_credit_name
  id: ArtistCreditName
  type: org.nanotek.beans.ArtistCreditName
  baseMap:  
    artistCredit: 0
    position: 1            
    artist: 2              
    name: 3                
    joinPhrase: 4    
 
artistcreditnamebean:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist_credit_name
  id: ArtistCreditNameBean
  type: org.nanotek.beans.csv.ArtistCreditNameBean
  baseMap:  
    artistCreditId: 0
    position: 1            
    artistId: 2              
    name: 3                
    joinPhrase: 4      
    
    
releasebean: 
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: release
  id: ReleaseBean
  type: org.nanotek.beans.csv.ReleaseBean 
  baseMap: 
    id: 0 
    gid: 1 
    name: 2
    artistCreditId: 3 
    releaseGroup: 4 
    status: 5 
    packaging: 6 
    language: 7 
    script: 8
    barcode: 9 
    comment: 10 
    editsPending: 11 
    quality: 12 
    lastUpdated: 13
    
releasegroup: 
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: release_group
  id: ReleaseGroupBean
  type: org.nanotek.beans.csv.ReleaseGroupBean 
  baseMap:   
    releaseGroupId: 0 
    gid: 1 
    name: 2 
    artistCredit: 3 
    type: 4
    comment: 5 
    editsPending: 6
    lastUpdated: 7
 
recordingbean: 
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: recording
  id: RecordingBean
  type: org.nanotek.beans.csv.RecordingBean 
  baseMap:   
    id: 0
    gid: 1
    name: 2
    artistCredit: 3
    length: 4
    comment: 5
    editsPending: 6
    lastUpdated: 7
    video: 8

trackbean: 
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: track
  id: TrackBean
  type: org.nanotek.beans.csv.TrackBean 
  baseMap:    
    id: 0 
    gid: 1 
    recordingId: 2 
    medium: 3 
    position: 4 
    number: 5 
    name: 6 
    artistCreditId: 7 
    length: 8 
    editsPending: 8 
    lastUpdate: 9
    isDataTrack: 10
    
mediumbean: 
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: medium
  id: MediumBean
  type: org.nanotek.beans.csv.MediumBean 
  baseMap:     
    id: 0
    release: 1 
    position: 2
    format: 3 
    name: 4 
    editsPending: 5 
    lastUpdated: 6 
    trackCount: 7 
    