server:
  port: 8080
  
http:
    end-point: /core-base  


spring.datasource.hikari.connectionTimeout: 20000
spring.datasource.hikari.maximumPoolSize: 5

    
spring.datasource.url:  jdbc:postgresql://localhost:5432/springbootdb 
spring.datasource.username: postgres 
spring.datasource.password: Postgres123@   
spring.jpa.hibernate.ddl-auto: create-drop

spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
entitymanager.packagesToScan: org.nanotek

artist:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist
  id: Artist
  type: org.nanotek.beans.ArtistName
  baseMap:
    id: 0
    gid: 1
    name: 2
    sortName: 3
    begin-date-year: 4
    begin-date-month: 5
    begin-date-day: 6
    end-date-year: 7
    end-date-month: 8
    end-date-day: 9
    type: 10
    area: 11
    gender: 12 
    comment: 13
    edits-pending: 14
    last-updated: 15
    ended: 16

    
artis_alias:
  fileLocation: E:\\mbfile\\mbdump\\mbdump
  fileName: artist_alias
  id: ArtistAlias
  type: org.nanotek.beans.ArtistAlias
  baseMap:  
    id: 0
    artist: 1
    name: 2
    locale: 3
    edits_pending: 4
    last_updated: 5
    type: 6
    sort_name: 7
    begin_date_year: 8
    begin_date_month: 9
    begin_date_day: 10
    end_date_year: 11
    end_date_month: 12
    end_date_day: 13
    primary_for_locale: 14
    ended: 15